"""initial_schema

Revision ID: 6683be157420
Revises: 
Create Date: 2026-10-07 10:29:59.626193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6683be157420'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('segment', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('slug', name=op.f('uq_companies_slug'))
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('analysis_runs',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_analysis_runs_company_id_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_runs'))
    )
    op.create_index(op.f('ix_analysis_runs_company_id'), 'analysis_runs', ['company_id'], unique=False)
    op.create_table('company_memberships',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_title', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_memberships_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_company_memberships_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_memberships')),
    sa.UniqueConstraint('company_id', 'user_id', name='uq_memberships_company_user')
    )
    op.create_index(op.f('ix_company_memberships_company_id'), 'company_memberships', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_memberships_user_id'), 'company_memberships', ['user_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('benefit_type', sa.Enum('revenue', 'cost_saving', name='benefit_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('potential_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cost_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('extra_clients', sa.Integer(), nullable=False),
    sa.Column('effort', sa.Enum('Baixo', 'Médio', 'Alto', name='effort_level', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 100', name=op.f('ck_opportunities_valid_confidence')),
    sa.CheckConstraint('cost_amount >= 0', name=op.f('ck_opportunities_nonnegative_cost')),
    sa.CheckConstraint('extra_clients >= 0', name=op.f('ck_opportunities_nonnegative_clients')),
    sa.CheckConstraint('horizon_days > 0', name=op.f('ck_opportunities_positive_horizon')),
    sa.CheckConstraint('potential_amount >= 0', name=op.f('ck_opportunities_nonnegative_potential')),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], name=op.f('fk_opportunities_analysis_run_id_analysis_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_opportunities_company_id_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities'))
    )
    op.create_index(op.f('ix_opportunities_analysis_run_id'), 'opportunities', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_opportunities_company_id'), 'opportunities', ['company_id'], unique=False)
    op.create_table('risks',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('Financeiro', 'Estoque', 'Operação', 'Pessoas', name='risk_category', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('cause', sa.Text(), nullable=False),
    sa.Column('probability', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('impact_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('Ativo', 'Em análise', 'Monitorando', name='risk_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('severity', sa.Enum('normal', 'atencao', 'critico', name='risk_severity', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('impact_amount >= 0', name=op.f('ck_risks_nonnegative_impact')),
    sa.CheckConstraint('probability BETWEEN 0 AND 100', name=op.f('ck_risks_valid_probability')),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], name=op.f('fk_risks_analysis_run_id_analysis_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_risks_company_id_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risks'))
    )
    op.create_index(op.f('ix_risks_analysis_run_id'), 'risks', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_risks_company_id'), 'risks', ['company_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.Enum('normal', 'atencao', 'critico', name='timeline_severity', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cause', sa.Text(), nullable=False),
    sa.Column('impact_description', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], name=op.f('fk_timeline_events_analysis_run_id_analysis_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_timeline_events_company_id_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_events'))
    )
    op.create_index(op.f('ix_timeline_events_analysis_run_id'), 'timeline_events', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_company_id'), 'timeline_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_event_date'), 'timeline_events', ['event_date'], unique=False)
    op.create_table('user_company_preferences',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('alert_risks', sa.Boolean(), nullable=False),
    sa.Column('alert_opportunities', sa.Boolean(), nullable=False),
    sa.Column('alert_weekly', sa.Boolean(), nullable=False),
    sa.Column('alert_capacity', sa.Boolean(), nullable=False),
    sa.Column('horizon_days', sa.SmallInteger(), nullable=False),
    sa.Column('sensitivity', sa.Enum('conservadora', 'equilibrada', 'agressiva', name='forecast_sensitivity', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('horizon_days IN (7, 15, 30)', name=op.f('ck_user_company_preferences_valid_horizon')),
    sa.ForeignKeyConstraint(['membership_id'], ['company_memberships.id'], name=op.f('fk_user_company_preferences_membership_id_company_memberships'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membership_id', name=op.f('pk_user_company_preferences'))
    )
    op.create_table('risk_recommendations',
    sa.Column('risk_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('position >= 0', name=op.f('ck_risk_recommendations_nonnegative_position')),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], name=op.f('fk_risk_recommendations_risk_id_risks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_recommendations')),
    sa.UniqueConstraint('risk_id', 'position', name='uq_risk_recommendations_position')
    )
    op.create_table('simulation_runs',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=True),
    sa.Column('opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('decision_kind', sa.Enum('marketing', 'stock', 'hire', 'price', 'unit', 'opportunity', name='decision_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=2000), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('assumption', sa.Text(), nullable=False),
    sa.Column('additional_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('incremental_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(decision_kind = 'opportunity' AND opportunity_id IS NOT NULL) OR (decision_kind <> 'opportunity' AND opportunity_id IS NULL)", name=op.f('ck_simulation_runs_opportunity_matches_decision')),
    sa.CheckConstraint('additional_cost >= 0', name=op.f('ck_simulation_runs_nonnegative_additional_cost')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_simulation_runs_nonnegative_amount')),
    sa.CheckConstraint('horizon_days > 0', name=op.f('ck_simulation_runs_positive_horizon')),
    sa.CheckConstraint('initial_capital >= 0', name=op.f('ck_simulation_runs_nonnegative_initial_capital')),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], name=op.f('fk_simulation_runs_analysis_run_id_analysis_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_simulation_runs_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['company_memberships.id'], name=op.f('fk_simulation_runs_created_by_membership_id_company_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_simulation_runs_opportunity_id_opportunities'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_runs'))
    )
    op.create_index(op.f('ix_simulation_runs_analysis_run_id'), 'simulation_runs', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_company_id'), 'simulation_runs', ['company_id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_created_by_membership_id'), 'simulation_runs', ['created_by_membership_id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_opportunity_id'), 'simulation_runs', ['opportunity_id'], unique=False)
    op.create_table('timeline_event_recommendations',
    sa.Column('timeline_event_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('position >= 0', name=op.f('ck_timeline_event_recommendations_nonnegative_position')),
    sa.ForeignKeyConstraint(['timeline_event_id'], ['timeline_events.id'], name=op.f('fk_timeline_event_recommendations_timeline_event_id_timeline_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_event_recommendations')),
    sa.UniqueConstraint('timeline_event_id', 'position', name='uq_timeline_recommendations_position')
    )
    op.create_table('saved_scenarios',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('simulation_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['company_memberships.id'], name=op.f('fk_saved_scenarios_membership_id_company_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation_runs.id'], name=op.f('fk_saved_scenarios_simulation_id_simulation_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_scenarios')),
    sa.UniqueConstraint('membership_id', 'simulation_id', name='uq_saved_scenarios_membership_simulation')
    )
    op.create_index(op.f('ix_saved_scenarios_membership_id'), 'saved_scenarios', ['membership_id'], unique=False)
    op.create_index(op.f('ix_saved_scenarios_simulation_id'), 'saved_scenarios', ['simulation_id'], unique=False)
    op.create_table('simulation_metrics',
    sa.Column('simulation_id', sa.Uuid(), nullable=False),
    sa.Column('variant', sa.Enum('baseline', 'simulated', name='simulation_variant', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('investment', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('clients', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('capacity >= 0', name=op.f('ck_simulation_metrics_nonnegative_capacity')),
    sa.CheckConstraint('clients >= 0', name=op.f('ck_simulation_metrics_nonnegative_clients')),
    sa.CheckConstraint('investment >= 0', name=op.f('ck_simulation_metrics_nonnegative_investment')),
    sa.CheckConstraint('revenue >= 0', name=op.f('ck_simulation_metrics_nonnegative_revenue')),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation_runs.id'], name=op.f('fk_simulation_metrics_simulation_id_simulation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('simulation_id', 'variant', name=op.f('pk_simulation_metrics'))
    )
    op.create_table('simulation_recommendations',
    sa.Column('simulation_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('position >= 0', name=op.f('ck_simulation_recommendations_nonnegative_position')),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation_runs.id'], name=op.f('fk_simulation_recommendations_simulation_id_simulation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_recommendations')),
    sa.UniqueConstraint('simulation_id', 'position', name='uq_simulation_recommendations_position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_recommendations')
    op.drop_table('simulation_metrics')
    op.drop_index(op.f('ix_saved_scenarios_simulation_id'), table_name='saved_scenarios')
    op.drop_index(op.f('ix_saved_scenarios_membership_id'), table_name='saved_scenarios')
    op.drop_table('saved_scenarios')
    op.drop_table('timeline_event_recommendations')
    op.drop_index(op.f('ix_simulation_runs_opportunity_id'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_created_by_membership_id'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_company_id'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_analysis_run_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_table('risk_recommendations')
    op.drop_table('user_company_preferences')
    op.drop_index(op.f('ix_timeline_events_event_date'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_company_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_analysis_run_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_risks_company_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_analysis_run_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_opportunities_company_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_analysis_run_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_company_memberships_user_id'), table_name='company_memberships')
    op.drop_index(op.f('ix_company_memberships_company_id'), table_name='company_memberships')
    op.drop_table('company_memberships')
    op.drop_index(op.f('ix_analysis_runs_company_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_table('users')
    op.drop_table('companies')
    # ### end Alembic commands ###
