/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as LinhaDoTempoRouteImport } from './routes/linha-do-tempo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OportunidadesRouteImport } from './routes/oportunidades'
import { Route as RiscosRouteImport } from './routes/riscos'
import { Route as SimuladorRouteImport } from './routes/simulador'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LinhaDoTempoRoute = LinhaDoTempoRouteImport.update({
  id: '/linha-do-tempo',
  path: '/linha-do-tempo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesRoute = OportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const RiscosRoute = RiscosRouteImport.update({
  id: '/riscos',
  path: '/riscos',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/linha-do-tempo': typeof LinhaDoTempoRoute
  '/login': typeof LoginRoute
  '/oportunidades': typeof OportunidadesRoute
  '/riscos': typeof RiscosRoute
  '/simulador': typeof SimuladorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/linha-do-tempo': typeof LinhaDoTempoRoute
  '/login': typeof LoginRoute
  '/oportunidades': typeof OportunidadesRoute
  '/riscos': typeof RiscosRoute
  '/simulador': typeof SimuladorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/linha-do-tempo': typeof LinhaDoTempoRoute
  '/login': typeof LoginRoute
  '/oportunidades': typeof OportunidadesRoute
  '/riscos': typeof RiscosRoute
  '/simulador': typeof SimuladorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistente'
    | '/configuracoes'
    | '/linha-do-tempo'
    | '/login'
    | '/oportunidades'
    | '/riscos'
    | '/simulador'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistente'
    | '/configuracoes'
    | '/linha-do-tempo'
    | '/login'
    | '/oportunidades'
    | '/riscos'
    | '/simulador'
  id:
    | '__root__'
    | '/'
    | '/assistente'
    | '/configuracoes'
    | '/linha-do-tempo'
    | '/login'
    | '/oportunidades'
    | '/riscos'
    | '/simulador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenteRoute: typeof AssistenteRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  LinhaDoTempoRoute: typeof LinhaDoTempoRoute
  LoginRoute: typeof LoginRoute
  OportunidadesRoute: typeof OportunidadesRoute
  RiscosRoute: typeof RiscosRoute
  SimuladorRoute: typeof SimuladorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linha-do-tempo': {
      id: '/linha-do-tempo'
      path: '/linha-do-tempo'
      fullPath: '/linha-do-tempo'
      preLoaderRoute: typeof LinhaDoTempoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades': {
      id: '/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof OportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riscos': {
      id: '/riscos'
      path: '/riscos'
      fullPath: '/riscos'
      preLoaderRoute: typeof RiscosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistenteRoute: AssistenteRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  LinhaDoTempoRoute: LinhaDoTempoRoute,
  LoginRoute: LoginRoute,
  OportunidadesRoute: OportunidadesRoute,
  RiscosRoute: RiscosRoute,
  SimuladorRoute: SimuladorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
